### ISSUE TITLE
Language provider error (SOLVED NNEDED 1.19.2)

### ISSUE THREAD

**Issue by EitaniTheAvali** [createbufferandbeams/createbufferandbeams-dev#1]
![image](https://user-images.githubusercontent.com/87674682/222935405-d442bb8d-1a6a-45d6-b8ff-1eb482e885e7.png)

I launched minecraft on 1.18.2 and got this issue

**Comment by natejw** [comment]
Your forge is the wrong version we run on 1.19.2, if you use other mods also mixed in that are not 1.19.2 you could also get this error. Please run this mod on Forge 1.19.2
